import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import type { Metadata } from 'next'

import AppTheme from '@/theme/AppTheme'
import { inter } from '@/theme/themePrimitives'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body suppressHydrationWarning className={inter.variable}>
        <AppRouterCacheProvider>
          <AppTheme>
            {children}
          </AppTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
